spring.datasource.url=jdbc:postgresql://localhost:5432/meeting_assistant?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
file.upload-dir=uploads

jwt.secret=REPLACE_WITH_YOUR_OWN_GENERATED_SECRET
groq.api.key=REPLACE_WITH_YOUR_OWN_GROQ_KEY